### ISSUE TITLE
Get error message

### ISSUE THREAD

**Issue by ivansabik** [BlueBiteLLC/service-geolocate-lite-js#1]
I want to see if there is another way to get the error message on fail. The only solution I came up with was with the detail property from CustomEvent:

`document.body.dispatchEvent(new CustomEvent('onLocateFail', { 'detail': e.message }));`

And then:

```
_handleLocateFail = function(e) {
      document.getElementById('latlon').innerHTML = e.detail;
    }
```

For that I needed to change the core geo-lite.js, any hints on how to achieve this in other way? thanks

**Comment by matt-oconnell** [comment]
@ivansabik This is a great solution. If you'd like to open a pull request, I'll merge it. Otherwise, I'll add this in on our end.

**Comment by ivansabik** [comment]
Hi matt, Just created a pull request that passes detail to CustomEvent. Please review since I also removed console.log calls which I dont like having in code I would eventually use in production. Also indentation with spaces but those are not really relevant.

https://github.com/BlueBiteLLC/service-geolocate-lite-js/pull/2

Cheers!

**Comment by ivansabik** [comment]
Merged #2

**Comment by matt-oconnell** [comment]
@ivansabik. This looks good. Thanks for the contribution!

**Comment by ivansabik** [comment]
You're very welcome :+1:
